#theme: jekyll-theme-slate

# Build settings
source: .
includes_dir: ./_includes
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
  parse_block_html: true
  footnote_nr: 1
permalinks: pretty
# safe: true
markdown_ext: "markdown,mkdown,mkdn,mkd,md,gfm"

plugins:
  - jekyll-spaceship
