#theme: jekyll-theme-slate

# Build settings
source: .
includes_dir: ./_includes
destination: ./_site
markdown: kramdown
# don't change the following; coderay will break the embedded
# annotations.
kramdown:
  enable_coderay: false
permalinks: pretty
# safe: true
markdown_ext: md